spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.drpycecnpepgwtawpoan
spring.datasource.password=FlashBasket@321
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
server.port=8081
razorpay.key.id=rzp_test_SqOq7zwDOvd03s
razorpay.key.secret=kj1Z7bPoMB79HzDlJt4G6qqI
